### ISSUE TITLE
输入 aes_cbc加密的key和IV

### ISSUE THREAD

**Issue by Streeeet** [Limour-dev/secret_actions#1]
请问第六步中 key 和 IV 是什么？

**Comment by Streeeet** [comment]
爱语飞飞提醒我用户名和密码错误，跟这个有关系吗？

**Comment by Limour-dev** [comment]
aes_cbc 的 密码 和 盐。这是自己设置的，如果要使用这个仓库的话，建议了解一下AES CBC加密。

**Comment by Limour-dev** [comment]
> 爱语飞飞提醒我用户名和密码错误，跟这个有关系吗？
没有关系，估计是你快识别的账号密码写错了

**Comment by Streeeet** [comment]
Thanks♪(･ω･)ﾉ
